### ISSUE TITLE
can't load the model

### ISSUE THREAD

**Issue by countback** [huggingface/pytorch-pretrained-BERT#353]
>>> model = BertModel.from_pretrained('bert-large-cased')
Model name 'bert-large-cased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-cased.tar.gz' was a path or url but couldn't find any file associated to this path or url.

**Comment by thomwolf** [comment]
Strange error.

Can you try:
```python
import pytorch_pretrained_bert as ppb
assert 'bert-large-cased' in ppb.modeling.PRETRAINED_MODEL_ARCHIVE_MAP
```
Do you have an open internet connection on the server that run the script?

**Comment by erip** [comment]
@thomwolf Is there a way to point to a model on disk?

**Comment by martiansideofthemoon** [comment]
I noticed that this error happens when you exceed the disk space in the temporary directory while downloading BERT.

**Comment by AmazingGzZc** [comment]
I ran into the same problem. When I used the Chinese pre-training model, it was sometimes good and sometimes bad.

**Comment by DuncanCam-Stein** [comment]
@thomwolf I've been having the same error, and I received an AssertionError when I try 

assert 'bert-based-uncased' in bert.modeling.PRETRAINED_MODEL_ARCHIVE_MAP

I've tried using both conda install and Pip install to get the package but in both cases I am not able to load any models

**Comment by thomwolf** [comment]
Hi @DuncanCam-Stein,
Which version of python do you have?
Can you try to install from source?

**Comment by DuncanCam-Stein** [comment]
@thomwolf  @countback  
I finally fixed the problem by downloading the tf checkpoints directly from [here](https://github.com/google-research/bert), and then using the 'convert_tf_checkpoint_to_pytorch.py' function to create a `pytorch_model.bin` file.
I then passed a path to pytorch_model.bin and bert_config.json file to from_pretrained which it was able to read.
That did the trick 👍 Helpful info was found [here](https://devhub.io/repos/huggingface-pytorch-pretrained-BERT).

**Comment by thomwolf** [comment]
The network connection check has been relaxed in the now merged #500.
Serialization of the model have also been simplified a lot with #489.

These improvements will be included in the next PyPI release (probably next week).

In the meantime you can install from `master` and already use the serialization best-practices described in the README [here](https://github.com/huggingface/pytorch-pretrained-BERT#serialization-best-practices)

**Comment by Colanim** [comment]
As @martiansideofthemoon said, I met this error if I didn't have enough space on disk.

Check if you can download the file with :

`wget https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz`

**Comment by Hannabrahman** [comment]
@martiansideofthemoon What does that mean if we can download it via wget but not when we use from_pretrained? is it a disk space problem?

**Comment by Colanim** [comment]
@Hannabrahman 
If you can download it via wget, it means you have enough disk space, so the issue is from somewhere else.

**Comment by Hannabrahman** [comment]
@Colanim Thanks. I figured out it was memory issue on the cache directory.

**Comment by raj5287** [comment]
@Hannabrahman 

> @Colanim Thanks. I figured out it was memory issue on the cache directory.

how did you solve this issue?

**Comment by Colanim** [comment]
@raj5287 
Free some disk space on the cache directory or specify another cache directory

**Comment by raj5287** [comment]
@Colanim i have enough disk space since i have downloaded the file using 
`wget https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz` but i am not sure how to specify another cache directory or use the downloaded file (i am new to pytorch and ubuntu :|)

**Comment by raj5287** [comment]
> @thomwolf @countback
> I finally fixed the problem by downloading the tf checkpoints directly from [here](https://github.com/google-research/bert), and then using the '[convert_tf_checkpoint_to_pytorch.py](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/convert_tf_checkpoint_to_pytorch.py)' function to create a `pytorch_model.bin` file.
> I then used the path to pytorch_model.bin and bert_config.json file in BertModel.from_pretrained('path/to/bin/and/json') instead of 'bert-base-uncased'.
> +1
> Helpful info was found [here](https://devhub.io/repos/huggingface-pytorch-pretrained-BERT).

@DuncanCam-Stein i have downloaded and placed _pytorch_model.bin_ and _bert_config.json_ in _bert_tagger_ folder but when i am doing `tokenizer = BertModel.from_pretrained('home/user/Download/bert_pos_tagger/bert_tagger/')` i am still getting the error : `Model name 'home/user/Downloads/bert_pos_tagger/bert_tagger/' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'home/user/Downloads/bert_pos_tagger/bert_tagger/' was a path or url but couldn't find any file associated to this path or url.`

**Comment by sherjy** [comment]
try to delete cahe file and rerun the command

**Comment by predictedblog** [comment]
I noticed that the error appears when I execute my script in debug mode (in Visual Studio Code). I fixed it by executing the script over the terminal `python myscriptname.py` once. Afterwards Debug mode works fine. 

Btw. I got the same problem with the tokenizer and this also fixed it.

**Comment by naveenjafer** [comment]
Is someone still facing this error? And where does it get downloaded to initially? @martiansideofthemoon you were mentioning about freeing up space in the temp dir? Is it a fixed location that it downloads to first?

**Comment by DTW1004** [comment]
> > > > model = BertModel.from_pretrained('bert-large-cased')
> > > > Model name 'bert-large-cased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-cased.tar.gz' was a path or url but couldn't find any file associated to this path or url.

hello，I meet the problem when run the torch bert code 👍 

OSError: Can't load weights for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-uncased' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.
if I can download the bert-base-uncased weight, where I should put the file in ? hope your reply~

**Comment by erip** [comment]
@DTW1004 check your network connection. This happens when I'm behind a proxy and SSL/proxy isn't configured appropriately.

**Comment by 1172100222** [comment]
bro，I've been having the same error. and then I try to debug the specific code
BertTokenizer.from_pretrained(MODEL_NAME)
step in to the origin code, I find  that I could step every line of the transformer in the debug mode. when step out origin code, the tokenizer tool could be used. what‘s more , the code could be run normaly in the next time I run the code.

**Comment by andiShan11** [comment]
I met the issue and I found the reason is that my server connecting was offline.

**Comment by dmr07** [comment]
Running into the same issue on AWS Lambda. Neither relative and absolute paths will allow the model to load from pre-trained.

**Comment by sayakpaul** [comment]
Here's what I am doing:

```shell
!wget -q https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-cased.tar.gz
!tar xf bert-base-multilingual-cased.tar.gz
```

Now, if I do:

```python
encoder = TFBertModel.from_pretrained("bert-base-multilingual-cased")
```

I still get:

```shell
OSError: Can't load config for 'bert-base-multilingual-cased'. Make sure that:

- 'bert-base-multilingual-cased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-multilingual-cased' is the correct path to a directory containing a config.json file
```

**Comment by apkbala107** [comment]
> Here's what I am doing:
> 
> from transformers import pipeline
> 
> def corret_sentence(sentence,unmasker): res = unmasker(sentence) return res
> 
> if **name**=='**main**': sentence = "关小彤" new_sentence = "" unmasker = pipeline('fill-mask', model='uer/chinese_roberta_L-2_H-512') for idx,ch in enumerate(sentence): new_sentence = sentence[:idx] + "[MASK]" + sentence[idx+1:] print(corret_sentence(new_sentence,unmasker))
> 
> I get:
> 
> ValueError: Could not load model uer/chinese_roberta_L-2_H-512 with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForMaskedLM'>, <class 'transformers.models.bert.modeling_bert.BertForMaskedLM'>).

how could solve this?


did you solve this problem?

i am also having sample

**Comment by Sharique-stack** [comment]
> @thomwolf @countback I finally fixed the problem by downloading the tf checkpoints directly from [here](https://github.com/google-research/bert), and then using the '[convert_tf_checkpoint_to_pytorch.py](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/convert_tf_checkpoint_to_pytorch.py)' function to create a `pytorch_model.bin` file. I then used the path to pytorch_model.bin and bert_config.json file in BertModel.from_pretrained('path/to/bin/and/json') instead of 'bert-base-uncased'. 👍 Helpful info was found [here](https://devhub.io/repos/huggingface-pytorch-pretrained-BERT).

Can you please specify which model exactly you downloaded and how you ran the function? Thanks
